name: build front- & backend
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: build frontend
        run: |
          cd frontend
          npm ci
          npm run build

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml